import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import "../assets/globals.css";

export const metadata: Metadata = {
    title: "Pijay",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-[#36454F] [&::-webkit-scrollbar]:hidden">
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
